---
version: "3"

services:

  ecowitt2mqtt:
    build: .
    container_name: ecowitt2mqtt
    environment:
      LOG_LEVEL: DEBUG
      MQTT_BROKER: vernemq
      MQTT_PASSWORD: password
      MQTT_PORT: 1883
      MQTT_TOPIC: Test
      MQTT_USERNAME: ecowitt
      OUTPUT_UNIT_SYSTEM: imperial
    ports:
      - "8080:8080/tcp"
    restart: always

  vernemq:
    container_name: vernemq
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_USER_ECOWITT: "password"
    image: "vernemq/vernemq:1.11.0"
    ports:
      - "1883:1883/tcp"
    restart: always
    user: root
